### ISSUE TITLE
404 error when try to configure

### ISSUE THREAD

**Issue by geniolius** [ostrovok-team/redmine-webhook-plugin#6]
**Describe the bug**
I receive a 404 error when I try to configure the plugin.

**To Reproduce**
Administration - Plugins - Redmine Webhook Plugin - Configure

**Expected behavior**
It should display a configuration page

**Packages versions (please complete the following information):**
 - Redmine Webhook Plugin: 1.0.0
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.4.6-p354 (2019-04-01) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

**Comment by biozz** [comment]
Hi @geniolius!

Sorry for the inconvenience and late response. 

I checked your setup and found that 404 happens if the plugin directory is named different from `webhook`. This is not clear from the readme and I added a note about that in https://github.com/ostrovok-team/redmine-plugin-webhook/commit/2a9c4b65b6e29f858203ab60614b8b806ed5332f. Please rename the plugin directory and try again.
